# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c79b8903b35d6493644e68a87df46526cdf6d559de2e2bd645b2fd76bf889d5f2e2315e3986bea61f8a56da71d8ef41e6b4d95d53b3b413bc066789fc299c90d

test:
  secret_key_base: 208441653cde1bbae0b37594f8cd41b24e513a8339714ad757941e734922522359133042ff19d3dd78bbba119151eac2540fe6c54fd34530dba4c1c77fddf8ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
