source 'https://rubygems.org'

gem 'therubyracer'
gem 'rails', '4.2.0'
gem 'execjs','2.2.2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc


group :development, :test do
	gem 'sqlite3', '1.3.9'
	gem 'byebug'
	gem 'web-console', '~> 2.0'
	gem 'spring'
end

group :test do
	gem 'rspec-rails'
	gem 'minitest', '~> 5.5.1'
end

group :production do
	gem 'mysql2'
end